
if [ -z "$1" ]
  then
    echo "No argument supplied"
    return
fi

newlang=$1

mkdir "texts/${newlang}"
cd "texts/${newlang}"
mkdir articles dynamic static emails
cp ../en/articles/*.md articles/
cp ../en/dynamic/*.md dynamic/
cp ../en/static/*.md static/
cp ../en/emails/*.md emails/
cp ../en/translations.json translations.json
touch nonproduction
git add .
git commit -m "New language - ${newlang} - copy from English"
rm articles/*.md dynamic/*.md static/*.md emails/*.md
echo "{}" > translations.json
cd ../..

php other/validate/translate.php ${newlang}

# TODO add to metadata.json

git add .
git commit -m "Language - ${newlang} - generated by google translate"

echo ""
echo "Validating..."
php other/validate/strings.php ${newlang}
php other/validate/validate.php ${newlang}
